# Generated by Django 3.0 on 2024-08-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20240816_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Autorização'), ('EM_VISITA', 'Em Visita'), ('FINALIZADO', 'Visita Finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
